// 9 个 AI 站点配置 (从原 Electron 项目迁移)
// label: Tauri webview 标识 (仅 a-zA-Z0-9_/-:)
// name:  显示名称
// inputSelector / buttonSelector / submitType: DOM 注入用选择器
export default [
  {
    name: "DeepSeek",
    label: "deepseek",
    url: "https://chat.deepseek.com/",
    inputSelector: "textarea#chat-input, textarea",
    buttonSelector: null,
    submitType: "enter",
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"]',
  },
  {
    name: "通义千问 (Qwen)",
    label: "qwen",
    url: "https://www.qianwen.com/",
    inputSelector: 'div[contenteditable="true"][data-slate-editor="true"]',
    buttonSelector: 'button[aria-label="发送消息"]',
    submitType: "click",
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"], [class*="conversation"]',
    needsBeforeInput: true,
  },
  {
    name: "Kimi (Moonshot)",
    label: "kimi",
    url: "https://kimi.moonshot.cn/",
    inputSelector: 'div[contenteditable="true"]',
    buttonSelector: 'div[class*="sendButton"], button[class*="sendButton"]',
    submitType: "click",
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"], [class*="bubble"]',
  },
  {
    name: "字节豆包",
    label: "doubao",
    url: "https://www.doubao.com/",
    inputSelector: 'div[contenteditable="true"], textarea',
    buttonSelector: 'button[class*="send-btn"]',
    submitType: "click",
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"], [class*="bubble"]',
  },
  {
    name: "文心一言",
    label: "yiyan",
    url: "https://yiyan.baidu.com/",
    inputSelector: "#erp-text-input, div.yc-editor, div[contenteditable='true']",
    buttonSelector: 'div[class*="send-btn"], button[class*="send"]',
    submitType: "click",
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"], [class*="content"]',
  },
  {
    name: "腾讯元宝",
    label: "yuanbao",
    url: "https://yuanbao.tencent.com/",
    inputSelector: 'div[contenteditable="true"]',
    buttonSelector: 'div[class*="send-btn"], button[class*="send"]',
    submitType: "click",
    messageSelector: '[class*="message"], [class*="Message"], [class*="chat-item"], [class*="bubble"]',
    uaOverride: "app/tencent_yuanbao",
  },
  {
    name: "知乎直答",
    label: "zhida",
    url: "https://zhida.zhihu.com/",
    inputSelector: "textarea, div[contenteditable='true']",
    buttonSelector: null,
    submitType: "enter",
    messageSelector: '[class*="message"], [class*="Message"], [class*="answer"], [class*="content"]',
  },
  {
    name: "Google Gemini (需科学上网)",
    label: "gemini",
    url: "https://gemini.google.com/",
    inputSelector: 'div[contenteditable="true"]',
    buttonSelector: 'button[class*="send-button"]',
    submitType: "click",
    messageSelector: '[class*="message"], [class*="Message"], [class*="model-response"]',
  },
  {
    name: "ChatGPT (需科学上网)",
    label: "chatgpt",
    url: "https://chatgpt.com/",
    inputSelector: "#prompt-textarea",
    buttonSelector: 'button[data-testid="send-button"]',
    submitType: "click",
    messageSelector: '[class*="message"], [data-message-author-role="assistant"]',
  },
];
